### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by arim215** [hjdhjd/homebridge-ratgdo#24]
### Homebridge Ratgdo

v2.6.0

### Homebridge Platform and OS

Ubuntu 24.10 on PCEngines APU2

### Homebridge Version

v1.8.5

### Node Version

22.12.0

### Ratgdo ESPHome Firmware Version

v2024.11.3

### Describe the problem

Getting error in logs when RATGDO plugin is getting loaded.

The only other plugin is Hombebridge-gsh.

I have PIHOLE running on the same machine and UNIFI controller, but it doesn't seem to be related

### Homebridge HBR JSON configuration

```json
{
            "name": "Ratgdo",
            "options": [
                "Disable.Light",
                "Disable.Motion",
                "Disable.Log.Light",
                "Disable.Log.Motion",
                "Disable.Log.Obstruction",
                "Disable.Log.VehiclePresence",
                "Disable.Log.Opener",
                "Disable.Log.Opener.BCFF4D9057C8",
                "Disable.Log.Light.BCFF4D9057C8",
                "Disable.Log.Motion.BCFF4D9057C8",
                "Disable.Log.Obstruction.BCFF4D9057C8",
                "Disable.Log.VehiclePresence.BCFF4D9057C8",
                "Disable.Light.BCFF4D9057C8",
                "Disable.Motion.BCFF4D9057C8"
            ],
            "_bridge": {
                "username": "0E:AA:A0:04:A4:85",
                "port": 42743
            },
            "platform": "Ratgdo"
        },
```

### Relevant log output

```shell
[2024-12-06, 9:33:44 a.m.] [Ratgdo] Discovered: ratgdov2.5i (address: 192.168.107.125 mac: BCFF4D9057C8 ESPHome firmware: v2024.11.3 variant: ratgdo).
[2024-12-06, 9:33:44 a.m.] [Ratgdo] Configuring: ratgdov2.5i (address: 192.168.107.125 mac: BCFF4D9057C8 ESPHome firmware: v2024.11.3 variant: ratgdo).
[2024-12-06, 9:33:44 a.m.] [Ratgdo] ratgdov2 5i: Disabling the light.
[2024-12-06, 9:33:44 a.m.] [Ratgdo] ratgdov2 5i: Disabling the motion sensor.
TypeError: Cannot read properties of undefined (reading 'match')
    at file:///var/lib/homebridge/node_modules/homebridge-ratgdo/src/ratgdo-platform.ts:130:112
    at Array.map (<anonymous>)
    at RatgdoPlatform.discoverRatgdoDevice (file:///var/lib/homebridge/node_modules/homebridge-ratgdo/src/ratgdo-platform.ts:130:44)
    at Browser.emit (node:events:524:28)
    at Browser.addService (/var/lib/homebridge/node_modules/homebridge-ratgdo/node_modules/bonjour-service/src/lib/browser.ts:140:14)
    at /var/lib/homebridge/node_modules/homebridge-ratgdo/node_modules/bonjour-service/src/lib/browser.ts:111:26
    at Array.forEach (<anonymous>)
    at /var/lib/homebridge/node_modules/homebridge-ratgdo/node_modules/bonjour-service/src/lib/browser.ts:106:25
    at Array.forEach (<anonymous>)
    at EventEmitter.onresponse (/var/lib/homebridge/node_modules/homebridge-ratgdo/node_modules/bonjour-service/src/lib/browser.ts:98:34)
[2024-12-06, 9:33:44 a.m.] [Ratgdo] Child bridge process ended
[2024-12-06, 9:33:44 a.m.] [Ratgdo] Process Ended. Code: 1, Signal: null
[2024-12-06, 9:33:44 a.m.] Homebridge v1.8.5 (HAP v0.12.3) (Google Smart Home) is running on port 35010.
[2024-12-06, 9:33:44 a.m.] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[2024-12-06, 9:33:50 a.m.] [Google Smart Home] Connected (1) - wss://homebridge-gsh.iot.oz.nu
[2024-12-06, 9:33:51 a.m.] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[2024-12-06, 9:33:51 a.m.] [Homebridge UI] [homebridge-gsh] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[2024-12-06, 9:33:51 a.m.] [Homebridge UI] [homebridge-ratgdo] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[2024-12-06, 9:33:51 a.m.] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[2024-12-06, 9:33:51 a.m.] [Ratgdo] Restarting Process...
[2024-12-06, 9:33:53 a.m.] [Ratgdo] Launched child bridge with PID 34999
[2024-12-06, 9:33:54 a.m.] Registering platform 'homebridge-ratgdo.Ratgdo'
[2024-12-06, 9:33:54 a.m.] [Ratgdo] Loaded homebridge-ratgdo v2.6.0 child bridge successfully
[2024-12-06, 9:33:54 a.m.] Loaded 1 cached accessories from cachedAccessories.0EAAA004A485.
[2024-12-06, 9:33:54 a.m.] Homebridge v1.8.5 (HAP v0.12.3) (Ratgdo) is running on port 42743.
[2024-12-06, 9:33:54 a.m.] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[2024-12-06, 9:33:54 a.m.] [Ratgdo] Discovered: ratgdov2.5i (address: 192.168.107.125 mac: BCFF4D9057C8 ESPHome firmware: v2024.11.3 variant: ratgdo).
[2024-12-06, 9:33:54 a.m.] [Ratgdo] Configuring: ratgdov2.5i (address: 192.168.107.125 mac: BCFF4D9057C8 ESPHome firmware: v2024.11.3 variant: ratgdo).
[2024-12-06, 9:33:54 a.m.] [Ratgdo] ratgdov2 5i: Disabling the light.
[2024-12-06, 9:33:54 a.m.] [Ratgdo] ratgdov2 5i: Disabling the motion sensor.
TypeError: Cannot read properties of undefined (reading 'match')
    at file:///var/lib/homebridge/node_modules/homebridge-ratgdo/src/ratgdo-platform.ts:130:112
    at Array.map (<anonymous>)
    at RatgdoPlatform.discoverRatgdoDevice (file:///var/lib/homebridge/node_modules/homebridge-ratgdo/src/ratgdo-platform.ts:130:44)
    at Browser.emit (node:events:524:28)
    at Browser.addService (/var/lib/homebridge/node_modules/homebridge-ratgdo/node_modules/bonjour-service/src/lib/browser.ts:140:14)
    at /var/lib/homebridge/node_modules/homebridge-ratgdo/node_modules/bonjour-service/src/lib/browser.ts:111:26
    at Array.forEach (<anonymous>)
    at /var/lib/homebridge/node_modules/homebridge-ratgdo/node_modules/bonjour-service/src/lib/browser.ts:106:25
    at Array.forEach (<anonymous>)
    at EventEmitter.onresponse (/var/lib/homebridge/node_modules/homebridge-ratgdo/node_modules/bonjour-service/src/lib/browser.ts:98:34)
```

### Acknowledgment that you are only running non-beta firmware releases from Apple, ESPHome, or Ratgdo

- [X] I acknowledge that I am not running any beta firmwares or operating systems from Apple, ESPHome, or Ratgdo.

**Comment by felker** [comment]
I was in the middle of opening my own Issue for the same crash. I am running Homebridge on a Raspiberry Pi 3B with Raspberry Pi OS 11 Bullseye. Same Homebridge v1.8.5 as OP, but Node 22.11.0 and I have tried the plugin v2.6.0 and v2.5.0, which both have the same issue (both in a child bridge and outside of one)
```
[12/1/2024, 6:26:28 PM] [Ratgdo] Launched child bridge with PID 27695
[12/1/2024, 6:26:29 PM] Registering platform 'homebridge-ratgdo.Ratgdo'
[12/1/2024, 6:26:29 PM] [Ratgdo] Loaded homebridge-ratgdo v2.6.0 child bridge successfully
[12/1/2024, 6:26:29 PM] Loaded 1 cached accessories from cachedAccessories.0EE3CB4178E4.
[12/1/2024, 6:26:29 PM] [Ratgdo] Debug logging on. Expect a lot of data.
[12/1/2024, 6:26:29 PM] Homebridge v1.8.5 (HAP v0.12.3) (Ratgdo) is running on port 47833.
[12/1/2024, 6:26:29 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[12/1/2024, 6:26:30 PM] [Ratgdo] Discovered: ratgdov2.5i 88623a (address: 192.168.1.239 mac: D8BC3888623A ESPHome firmware: v2024.4.2 variant: ratgdo).
[12/1/2024, 6:26:30 PM] [Ratgdo] Configuring: ratgdov2.5i 88623a (address: 192.168.1.239 mac: D8BC3888623A ESPHome firmware: v2024.4.2 variant: ratgdo).
TypeError: Cannot read properties of undefined (reading 'match')
    at file:///usr/lib/node_modules/homebridge-ratgdo/src/ratgdo-platform.ts:130:112
    at Array.map (<anonymous>)
    at RatgdoPlatform.discoverRatgdoDevice (file:///usr/lib/node_modules/homebridge-ratgdo/src/ratgdo-platform.ts:130:44)
    at Browser.emit (node:events:518:28)
    at Browser.addService (/usr/lib/node_modules/homebridge-ratgdo/node_modules/bonjour-service/src/lib/browser.ts:140:14)
    at /usr/lib/node_modules/homebridge-ratgdo/node_modules/bonjour-service/src/lib/browser.ts:111:26
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-ratgdo/node_modules/bonjour-service/src/lib/browser.ts:106:25
    at Array.forEach (<anonymous>)
    at EventEmitter.onresponse (/usr/lib/node_modules/homebridge-ratgdo/node_modules/bonjour-service/src/lib/browser.ts:98:34)
[12/1/2024, 6:26:30 PM] [Ratgdo] Child bridge process ended
[12/1/2024, 6:26:30 PM] [Ratgdo] Process Ended. Code: 1, Signal: null
```

Recently upgraded my Homebridge UI version and some other plugins (deCONZ, LG ThinQ, Nest, UniFi Protect), so that must be related

**Comment by felker** [comment]
Just tested v2.3.3 and v2.4.0 of the plugin, and they work fine. So it appears the bug was introduced in v2.5.0

**Comment by hjdhjd** [comment]
Thanks, will be fixed in a release shortly.

**Comment by hjdhjd** [comment]
Give v2.6.1 a go. Thanks!

**Comment by felker** [comment]
No luck. Now it seems to be dying during device discovery of another (non-ratgdo) ESPHome device:
```
[12/6/2024, 7:50:57 PM] [Ratgdo] Discovered: ratgdov2.5i 88623a (address: 192.168.1.239 mac: D8BC3888623A ESPHome firmware: v2024.4.2 variant: ratgdo).
[12/6/2024, 7:50:57 PM] [Ratgdo] Configuring: ratgdov2.5i 88623a (address: 192.168.1.239 mac: D8BC3888623A ESPHome firmware: v2024.4.2 variant: ratgdo).
[12/6/2024, 7:50:57 PM] [Ratgdo] Discovered: undefined (address: 192.168.1.60 mac: 08D1F981DDB8 ESPHome firmware: v2024.5.4 variant: konnected).
TypeError: Cannot read properties of undefined (reading 'replace')
    at validateName (file:///usr/lib/node_modules/homebridge-ratgdo/node_modules/homebridge-plugin-utils/src/util.ts:92:15)
    at RatgdoPlatform.configureGdo (file:///usr/lib/node_modules/homebridge-ratgdo/src/ratgdo-platform.ts:361:50)
    at RatgdoPlatform.discoverRatgdoDevice (file:///usr/lib/node_modules/homebridge-ratgdo/src/ratgdo-platform.ts:142:34)
    at Browser.emit (node:events:518:28)
    at Browser.addService (/usr/lib/node_modules/homebridge-ratgdo/node_modules/bonjour-service/src/lib/browser.ts:140:14)
    at /usr/lib/node_modules/homebridge-ratgdo/node_modules/bonjour-service/src/lib/browser.ts:111:26
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-ratgdo/node_modules/bonjour-service/src/lib/browser.ts:106:25
    at Array.forEach (<anonymous>)
    at EventEmitter.onresponse (/usr/lib/node_modules/homebridge-ratgdo/node_modules/bonjour-service/src/lib/browser.ts:98:34)
```

**Comment by hjdhjd** [comment]
Let’s try this once more - v2.6.2 should do the trick.

**Comment by felker** [comment]
Still failing. Traceback i s gone, just shows dead after detecting the `undefined` (Emporia Vue 3) device
```
[12/6/2024, 8:41:11 PM] [Ratgdo] Process Ended. Code: 1, Signal: null
[12/6/2024, 8:41:18 PM] [Ratgdo] Restarting Process...
[12/6/2024, 8:41:20 PM] [Ratgdo] Launched child bridge with PID 10930
[12/6/2024, 8:41:21 PM] [Ratgdo] Loaded homebridge-ratgdo v2.6.2 child bridge successfully
[12/6/2024, 8:41:22 PM] [Ratgdo] Discovered: ratgdov2.5i 88623a (address: 192.168.1.239 mac: D8BC3888623A ESPHome firmware: v2024.4.2 variant: ratgdo).
[12/6/2024, 8:41:22 PM] [Ratgdo] Configuring: ratgdov2.5i 88623a (address: 192.168.1.239 mac: D8BC3888623A ESPHome firmware: v2024.4.2 variant: ratgdo).
[12/6/2024, 8:41:22 PM] [Ratgdo] Discovered: undefined (address: 192.168.1.60 mac: 08D1F981DDB8 ESPHome firmware: v2024.5.4 variant: konnected).
[12/6/2024, 8:41:22 PM] [Ratgdo] Child bridge process ended
[12/6/2024, 8:41:22 PM] [Ratgdo] Process Ended. Code: 1, Signal: null
```

**Comment by hjdhjd** [comment]
Teaches me to address something when I'm exhausted after a long week. LOL...give v2.6.3 a go. Should do the trick.

**Comment by felker** [comment]
Working now, thanks!

**Comment by arim215** [comment]
Thank you for the quick fix!!
